controllers/databasecluster_controller.go

Ports are hardcoded on the operator level and there's no point of getting them from services

EVEREST-168 Added ports for database clusters

---

api/v1alpha1/databaseengine_types.go

- In case DBEngine has not been properly initialized we panicked
- The panic came from DBCluster controller
- DBEngine did not have enough time to be initialize

Fix panic in allowed versions

---

Makefile
api/v1alpha1/databasecluster_types.go
bundle/manifests/everest-operator.clusterserviceversion.yaml
bundle/manifests/everest.percona.com_databaseclusters.yaml
config/crd/bases/everest.percona.com_databaseclusters.yaml
config/manager/kustomization.yaml
controllers/databasecluster_controller.go
deploy/bundle.yaml

EVEREST-324
Dropped sharded mongo because it should be done in a different way and we received feedback to have this option in the UI. Until then we do not support sharded mongo instances.
Toggling unsafeConfigurations from true to false and vice versa may lead to unexpected behavior in operator

EVEREST-324 Fixed scaling for pxc and psmdb

---

controllers/databasecluster_controller.go

EVEREST-357
Reduce the size of the restore name to avoid exceeding the RFC1123 limit.

EVEREST-357 reduce size of the restore name

---

controllers/databasecluster_controller.go
e2e-tests/tests/dbbackup_pg/00-assert.yaml
e2e-tests/tests/dbbackup_psmdb/00-assert.yaml
e2e-tests/tests/dbbackup_pxc/00-assert.yaml

EVEREST-392
* The PMM ServerHost can't contain the protocol nor the port, we must pass only the hostname.
* PMM API key integration with cluster secrets:
* In order to keep auto-generating the rest of the cluster secret's data in PXC we can't create a secret with just the PMM API key. We need to wait for the secret to be autogenerated and then update it with the PMM API key.
* In PSMDB we can create the secret right away with just the PMM API key and the rest of the secret's data will still be auto-generated.
* In PG we shall not use the separate secret as the users. This can be
created before the DB because the operator doesn't change this secret.
P.S. I didn't update the e2e tests, too tired for it right now and we need to get this into the release tomorrow but I did test it manually. …

EVEREST-392 fix PMM monitoring

---

controllers/databaseclusterrestore_controller.go

By changing the DB cluster state to "restoring" when a restoration is in progress we introduced a deadlock where the restore isn't able to be updated because it's waiting for the DB to be ready and the DB won't ever be ready while the restore isn't ready. In this commit we also accept the DB restoring state to reconcile the restore CR which removes the deadlock.

EVEREST-397 fix PSMDB restore deadlock

---

controllers/databasecluster_controller.go
controllers/databasecluster_controller_test.go

EVEREST-380
- IP source range did not support IP without a subnet
- This commit adds support for IPs by adding a /32 subnet automatically

EVEREST-380: support IP without subnet

---

controllers/databasecluster_controller.go
controllers/databasecluster_controller_test.go
controllers/databaseclusterbackup_controller.go
e2e-tests/tests/features/dbbackup_pg/20-assert.yaml
e2e-tests/tests/features/dbbackup_pg/40-assert.yaml
e2e-tests/tests/features/dbbackup_pg/50-assert.yaml
e2e-tests/tests/features/dbbackup_pg/60-assert.yaml
e2e-tests/tests/features/dbbackup_pg/70-assert.yaml
e2e-tests/tests/features/dbbackup_pg/70-scheduled-backup.yaml

EVEREST-433
We need to keep the PVC-based repo in the list even if the user defines a cloud-based repo because the PG operator will restart the cluster if the only repo in the list is changed.

EVEREST-433 fix pg restart on backup request

---

controllers/databasecluster_controller.go
e2e-tests/tests/core/pg/10-assert.yaml
e2e-tests/tests/core/pxc/10-assert.yaml

EVEREST-200
In the same way that PR #75 added the delete PVC finalizer that ensures the deletion of PVCs as well as the DB connection secrets we shall also add the delete SSL finalizer to delete the auto-generated SSL certs secrets.
We don't need any finalizer for PSMDB because the SSL secrets have an owner reference to the PerconaServerMongoDB CR so they get automatically deleted when the DB cluster is deleted.

EVEREST-200 delete SSL secrets

---

e2e-tests/tests/core/pg/40-delete-cluster.yaml
e2e-tests/tests/core/pg/41-wait-deletion.yaml
e2e-tests/tests/core/pg/90-delete-clusters.yaml
e2e-tests/tests/core/psmdb/40-delete-clusters.yaml
e2e-tests/tests/core/psmdb/41-wait-deletion.yaml
e2e-tests/tests/core/psmdb/50-assert.yaml
e2e-tests/tests/core/psmdb/50-create-single-node-cluster.yaml
e2e-tests/tests/core/psmdb/60-assert.yaml
e2e-tests/tests/core/psmdb/60-scale-cluster.yaml
e2e-tests/tests/core/psmdb/97-delete-clusters.yaml
e2e-tests/tests/core/pxc/40-delete-cluster.yaml
e2e-tests/tests/core/pxc/41-wait-deletion.yaml
e2e-tests/tests/core/pxc/97-delete-cluster.yaml
e2e-tests/tests/features/dbbackup_pg/90-delete-clusters.yaml
e2e-tests/tests/features/dbbackup_psmdb/90-delete-cluster.yaml
e2e-tests/tests/features/dbbackup_pxc/90-delete-cluster.yaml
e2e-tests/tests/features/monitoringconfig_pg/96-delete-clusters.yaml
e2e-tests/tests/features/monitoringconfig_psmdb/96-delete-clusters.yaml
e2e-tests/tests/features/monitoringconfig_pxc/96-delete-clusters.yaml
e2e-tests/tests/features/scheduled_backups/04-cleanup.yaml
e2e-tests/tests/features/templates/98-delete-clusters.yaml

---
**Problem:**
EVEREST-107
Once we enabled a manual cleanup step and used the `skipDelete` option for Kuttl sometimes it ended up with leftover pods running inside the cluster which may lead to flaky tests because of a lack of compute resources.
- [link]
**Cause:**
**Solution:**
Having proper cleanup and deletion of a database cluster on each step solves this issue some leftovers may be there but it makes everything more stable 
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-107 Proper cleanup after each step

---

Makefile
bundle/manifests/everest-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
config/manager/manager.yaml
deploy/bundle.yaml

---
**Problem:**
EVEREST-458
The default labels are not enough to be sure and list pods created by deployment efficiently 
**Solution:**
Added additional labels that we can use to query k8s API for getting the pod of the everest operator
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-458 Set labels for the manager for faster search

---

controllers/databasecluster_controller.go

---
**Problem:**
EVEREST-470
PXC backup container uses resources, but we do not set them . We need to set resources for backup as well.
**Solution:**
Since @hors reported the issue and had a discussion with him about this as the first solution. The operator adopted the default resources provided by operators in cr.yaml file. Yet, we should revisit this once we start working on templates
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-470 Set default resources for backup/proxy pods

---

controllers/databasecluster_controller.go

**Fix EKS external access LB annotation**
---
**Problem:**
EVEREST-568
It fails to get an external IP for the load balancer service in EKS.
- #126
**Cause:**
We were setting annotations that only apply to the new LB controller add-on. When this add-on isn't installed in the cluster the annotations are not accepted and a IP is not assigned.
**Solution:**
Set NLB but use the legacy controller's annotation. Chetan and Slava confirmed this is the way to go.
Tested it on EKS and it successfully gets an external IP from the load balancer.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-568 fix EKS external access LB annotation

---

bundle/manifests/everest-operator.clusterserviceversion.yaml
bundle/manifests/everest.percona.com_backupstorages.yaml
controllers/databaseclusterbackup_controller.go
deploy/bundle.yaml
e2e-tests/tests/features/dbbackup_psmdb/20-assert.yaml
e2e-tests/tests/features/dbbackup_psmdb/50-assert.yaml
e2e-tests/tests/features/dbbackup_psmdb/70-assert.yaml
e2e-tests/tests/features/dbbackup_psmdb/70-scheduled-backup.yaml

**Fix mongo scheduled backups**
---
**Problem:**
EVEREST-532
MongoDB scheduled backups didn't show the cluster name and thus weren't being properly reconciled. 
- #115
**Cause:**
In psmdb operator v1.15.0 the PSMDBCluster field is no longer being filled.
**Solution:**
Move to the new ClusterName field instead of PSMDBCluster.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-532 fix mongo scheduled backups

---

controllers/databasecluster_controller.go

**EVEREST-584 Fix PXC being stuck on pause after restore**
---
**Problem:**
EVEREST-584
PXC DB is suck on pause after restore.
**Cause:**
If any restore job is running then the DB paused spec must match the PXC pause spec. 
Previously, we were only considering the state of the last restore job in the list. If that last restore had already finished we wouldn't update the DB pause spec with the PXC pause spec.
**Solution:**
We need to make sure that any restore job for that given DB is considered when evaluating if a restore job is running.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-584 Fix PXC being stuck on pause after restore

---

bundle/manifests/everest-operator.clusterserviceversion.yaml
controllers/databasecluster_controller.go

---
**Problem:**
EVEREST-587
We did not wait for DB before initiating a restore.
**Cause:**
DB was not ready and the restore failed.
**Solution:**
Wait for DB before restore
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-587: wait for db before restore

---

controllers/databasecluster_controller.go

**EVEREST-636 increase PBM memory limit**
---
**Problem:**
EVEREST-636
PSMDB backup hangs due to lack of memory.
**Cause:**
PBM has bug that causes the backup to hang due to lack of memory.
**Solution:**
Ultimately, this is a PBM issue but from the everest side we try to avoid it by increasing the memory limit.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-636 increase PBM memory limit

---

api/v1alpha1/databaseclusterbackup_types.go
bundle/manifests/everest-operator.clusterserviceversion.yaml
bundle/manifests/everest.percona.com_databaseclusterbackups.yaml
config/crd/bases/everest.percona.com_databaseclusterbackups.yaml
controllers/databaseclusterbackup_controller.go
deploy/bundle.yaml
e2e-tests/tests/features/dbbackup_pxc/50-assert.yaml

**Detect PITR Gaps**
---
**Problem:**
EVEREST-604
**Cause:**
We want to show a message on the UI if there are gaps detected in pitr logs. There is a way for pxc to detect it, so this PR propagates this information to the `DatabaseClusterBackup` CR
**Solution:**
Add a new field to the `DatabaseClusterBackup` status

EVEREST-604 Detect pitr gaps

---

Makefile
bundle/manifests/everest-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
deploy/bundle.yaml

**New dev version**
---
**Problem:**
EVEREST-107

EVEREST-107 update version

---

.github/workflows/build-push-images.yaml
.github/workflows/checks.yml
Makefile
bundle/manifests/everest-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
deploy/bundle.yaml

**DEV pipelines**
---
**Problem:**
EVEREST-107
- add check for the default dev version
- add check for no source code changes
- update image tags 
- update the default codebase state for main branch (version 0.0.0)
more info about the new CI can be found the pipelines doc ticket EVEREST-481 
Related PRs:
- https://github.com/percona/percona-everest-cli/pull/258
- https://github.com/percona/everest-catalog/pull/2
- https://github.com/percona/percona-everest-backend/pull/374

EVEREST-107 dev pipelines

---

.github/workflows/ci.yml
controllers/databaseclusterbackup_controller.go

---
**Problem:**
EVEREST-739
Operator panics when the first PG backup is created after deploying a DB.
**Cause:**
Invalid index was referred to.
**Solution:**
Prevent `repo1` from being processed.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-739: fix panic for initial PG backup

---

.github/workflows/build-push-images.yaml

**Dev pipeline fix**
---
**Problem:**
EVEREST-405
Make the operator pipeline push the 0.0.0 image to perconalab on every commit to main

EVEREST-405 Push dev image

---

controllers/databasecluster_controller.go

**Fix editing monitoring label**
---
**Problem:**
EVEREST-808
EVEREST-810
If users changed the monitoring instance for a given cluster the label wouldn't change.
**Cause:**
We were only updating the monitoring label if it didn't exist.
**Solution:**
Update the monitoring label if it's different to the expected one. 
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-808 EVEREST-810 Fix editing monitoring label

---

controllers/databasecluster_controller.go

**Fix DBC restart race condition**
---
**Problem:**
EVEREST-768
During a DBC restart some pods aren't restarted.
**Cause:**
When pausing a PG cluster, the PG operator sets the STS replicas to 0 and sets the state to paused. Since the pods don't immediately go down, if we unpause the cluster the stateful set replicas will go up again and some pods might not be restarted.
**Solution:**
Wait for all pods to go down before reinitializing the DBC.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-768 Fix DBC restart race condition

---

controllers/databaseclusterbackup_controller.go
e2e-tests/tests/features/dbbackup_pg/20-assert.yaml
e2e-tests/tests/features/dbbackup_pg/50-assert.yaml

**Change PG backups type to full**
---
**Problem:**
EVEREST-826
PG on-demand backups were of type incremental instead of full.
**Cause:**
We didn't set any custom option and the default is incremental.
**Solution:**
Set the options to set the type to full.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-826 Change PG backups type to full

---

controllers/databasecluster_controller.go

**PG second restoration fix**
---
**Problem:**
EVEREST-822
PG cluster was stuck in initializing after the second restore.
**Cause:**
A restored from DataSource Database couldn't be restored again since the DataSource field was conflicting under the hood with the newest restoration process. 
**Solution:**
Clean up the DataSource field once PG cluster is ready
**CHECKLIST**
---
**Jira**
**Tests**

EVERST-822 Restoration fix

---

.github/workflows/ci.yml

---
**Problem:**
The e2e tests are failing as deletion of namespaces await proper cleanup of backupstorage resource
**Solution:**
Delete the backupstorage resource first so that the finalizer is handled correctly and namespace is allowed to be cleaned-up
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-107 | Fix e2e tests getting stuck on deletion of namespace

---

controllers/databaseclusterrestore_controller.go
e2e-tests/tests/features/dbbackup_pxc/51-assert.yaml

---
**Problem:**
[EVEREST-890](https://perconadev.atlassian.net/browse/EVEREST-890)
PITR restore of a MySQL to a new cluster fails.
**Cause:**
When performing a PITR for MySQL, the created pxc-restore object always assumes its own bucket as the backup source. This will not work when we want to PITR restore to a new cluster, as it should use the source cluster's bucket and not its own.
**Solution:**
Updated the PXC restore code so that it uses the same bucket as the one used for the source backup. This way it works for same-cluster and cross-cluster PITR restore.
**CHECKLIST**
---
**Jira**
**Tests**
[EVEREST-890]: https://perconadev.atlassian.net/browse/EVEREST-890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix MySQL PITR restore to new cluster

---

controllers/databasecluster_controller.go
e2e-tests/tests/core/pg/70-assert.yaml

**Enable track_commit_timestamp for PG**
---
**Problem:**
EVEREST-897
Force enable `track_commit_timestamp` option for PG
**Cause:**
A workaroud for the PITR restoration problem which appears when one tries to restore after the latest transaction.
**Solution:**
Temporary enable `track_commit_timestamp` option so that the user could easily get the date of the latest transaction by calling `select pg_last_committed_xact();`
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-897 Enable track_commit_timestamp

---

controllers/databasecluster_controller.go

**EVEREST-913 fix incorrect LB type for HAProxy replicas svc in EKS**
---
**Problem:**
EVEREST-913
In #132 we fixed an incorrect annotation for the HAProxy primary service's LB for EKS but we forgot to do the same for the HAProxy replicas service LB. This lead us to have a `network` LB for the primary service and a `classic` LB for the replicas.
We should set the same annotation for both services.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-913 fix incorrect LB type for HAProxy replicas svc in EKS

---

.github/workflows/ci.yml

---
**Problem:**
EVEREST-107
Tests are stuck on namespace deletion
**Cause:**
I observed that a namespace was stuck in termination due to a PG resource whose finalizers could not be cleaned-up. This may be due to the fact that the pg operator gets deleted upon ns deletion, even before it has had the change to handle the PG finalizers.
**Solution:**
Ensure that we delete `db` resources in foreground. This ensures that we wait for all child resources to be deleted first, so that any finalizers may be handled, before the operator is deleted.

EVEREST-107 | Fix e2e test timeouts in CI

---

controllers/databasecluster_controller.go

---
**Problem:**
EVEREST-939
When we have the PITR backupstroage different from the scheduled backups, the Secret from `everest-system` namespace is not copied.
**Solution:**
Ensure that Secrets are copied over similar to how we do for Scheduled backups.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-939 | Ensure Secrets for PITR BackupStorages are copied

---

api/v1alpha1/backupstorage_types.go
api/v1alpha1/zz_generated.deepcopy.go
bundle/manifests/everest-operator.clusterserviceversion.yaml
bundle/manifests/everest.percona.com_backupstorages.yaml
config/crd/bases/everest.percona.com_backupstorages.yaml
controllers/providers/pg/applier.go
deploy/bundle.yaml

**Support path-style URL access for Backup Storages**
---
**Problem:**
EVEREST-919
S3 compatible APIs can support two flavors of bucket hosting styles:
[Path-style](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#path-style-access)
[Virtual-hosted–style](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#virtual-hosted-style-access)
Currently everest only supports virtual-hosted style but we should also support the path-style.
**Solution:**
PXC and PSMDB automatically select path-style if needed. PGBackrest needs a config option.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-919 Support path-style URL access for Backup Storages

---

controllers/providers/pxc/applier.go
controllers/providers/pxc/mysqld_configs.go
controllers/providers/pxc/provider.go

---
**Problem:**
EVEREST-1020
The new mysql configs added in https://github.com/percona/everest-operator/pull/309 don't work for engine versions < 8.0.31
**Solution:**
We use the new configs only if the engine version is >= 8.0.31, otherwise we don't specify anything and use the defaults provided by the operator.
**CHECKLIST**
---
**Jira**

EVEREST-1020 | mysql config should be applied only for engine >=8.0.31

---

controllers/providers/pg/applier.go
controllers/providers/pg/provider.go

---
**Problem:**
EVEREST-1014
In https://github.com/percona/everest-operator/pull/378, we added a fix to remove the DataSource after the restore was complete. However, the case for PG was not handled correctly.
**Cause:**
The code where the DataSource for PG is removed, assumes that there will be a DatabaseRestore object created, and once it is Complete, the DataSource is set to nil. However, in the case for PG, we don't create DatabaseRestore object for initial restores.
**Solution:**
Do not depend on DatabaseRestores. Instead, check if the cluster is ready and unset the DataSource.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1014 | Fix removal of DataSource for PG restores

---

controllers/databaseclusterrestore_controller.go

---
**Problem:**
EVEREST-1036
The database is removed, but the restore still remains in the namespace.
**Cause:**
No mechanism to automatically delete the restore object was implemented
**Solution:**
Set DBR owner reference to DBC
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1036 Delete DBRestore CR when DBC CR is deleted

---

controllers/providers/pxc/provider.go

---
**Problem:**
EVEREST-1020
mysql configs are not being applied for version 8.0.31.
**Cause:**
Semver comparison takes the metadata portion into account as well. Currently we compare against `8.0.31`, however the input version to check for is `8.0.31-23.2`. The semver library takes the `-23.2` into account as well, which results in it being reported as "not equal".
```go
func main() {
minVer, _ := goversion.NewVersion("8.0.31")
engineVer, _ := goversion.NewVersion("8.0.31-23.2")
fmt.Println(engineVer.GreaterThanOrEqual(minVer))        // returns false
fmt.Println(engineVer.Core().GreaterThanOrEqual(minVer)) // returns true
}
```
**Solution:**
Compare only the core (ignore metadata)
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1020 | PXC should only compare semver core when applying mysql configs

---

controllers/databaseclusterbackup_controller.go
controllers/providers/pg/applier.go

---
**Problem:**
EVEREST-1054
PG restores do not work when using a backup storage location such as Minio.
**Cause:**
The restore issues are only caused when setting `forcePathStyle` and/or `verifyTLS=false`
The backup controller lists objects in the S3 storage to build the backup destination path. This S3 API call was failing as the client was not configured for skipping TLS checks or using path-style URIs.
When performing restores to a new cluster, we did not configure pgBackRest to skip TLS checks or force path-style URIs, depending on the backup storage.
**Solution:**
- Enforce TLS settings and URI style in S3 client while listing S3 objects in the backup controller
- Similarly, configure pgBackRest settings correctly when restoring to a new cluster. …

EVEREST-1054 | Fix PG restores for S3 compatible storage locations 

---

api/v1alpha1/databaseclusterbackup_types.go
controllers/databaseclusterbackup_controller.go

---
**Problem:**
EVEREST-1061
Backups should not be reconciled after they've completed.
**Why is this needed?**
When retentionCopies policy is set, the underlying operators will delete their backup CR. Everest operator sets a bi-directional owner reference between the dbbackup and the upstream backup CR. This could lead to a race condition where the upstream operator deletes the backup CR (due to retention settings) but the Everest operator re-creates it.
This can be fixed if the everest operator does not reconcile backups that have completed.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1061 | backups should not be reconciled after they've succeeded

---

controllers/databaseclusterbackup_controller.go
e2e-tests/tests/features/dbbackup_psmdb/70-assert.yaml

---
**Problem:**
EVEREST-1064
Duplicate backups are created when specifying a schedule for PSMDB.
**Cause:**
When a backup schedule is specified, PSMDBO automatically creates a psmdb-backup. Upon creation, the backup process starts. However, Everest then modifies the psmdb-backup object by setting an OwnerReference, which triggers another backup run for the same psmdb-backup object, resulting in duplicate backups.
**Solution:**
This is a known issue with PSMDBO, and a fix is expected. As a temporary workaround, Everest should wait for the psmdb-backup to progress beyond "waiting" to be able to adopt the object.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1064 | psmdb-backups should not be adopted by dbbackups until a status is observed

---

controllers/databaseclusterrestore_controller.go

---
**Problem:**
EVEREST-1082
The creation of a new MongoDB from a backup fails if the storage is using a self-signed certificate.
**Cause:**
We did not set the skip TLS verify option in the restore object.
**Solution:**
Set the skip TLS verify option in the restore object.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1082 Fix MongoDB restore to a new DB when storage is using a self-signed cert

---

controllers/databaseclusterbackup_controller.go
e2e-tests/tests/core/dbengine/10-assert.yaml
e2e-tests/tests/core/dbengine/20-assert.yaml

**Reconcile complete backups**
---
**Problem:**
EVEREST-912
**Why is this needed?**
Successful Everest backup CR needs to be reconciled because the gaps information appears on the pxc-backup resources which needs to be also reflected in the Everest backup. 
However, recently there were [the changes](https://github.com/percona/everest-operator/pull/399) which prevent the complete backups from reconciling because of the retention copies issue. 
This PR still keeps the complete backups from being recreated however the reconciliation still happens over the CR status.

EVEREST-912 Reconcile complete backups

---

controllers/backupstorage_controller.go

---
**Problem:**
EVEREST-900
Introduced a nil pointer dereference exception when merging the functionality of the secret reconciler into the backup storage reconciler.
**Cause:**
Introduced a nil pointer dereference exception when merging the functionality of the secret reconciler into the backup storage reconciler.
**Solution:**
Check for nil pointer first before assignment.

EVEREST-900 | [bug] Fix nil pointer deref exception

---

api/v1alpha1/databaseclusterbackup_types.go
controllers/databaseclusterbackup_controller.go

---
**Problem:**
EVEREST-1117
Status of PG DatabaseClusterBackups have their status constantly flip-flop between `Succeeded` and `None`
- https://github.com/percona/everest-operator/pull/406
**Cause:**
We recently made a change where if a backup is complete, the spec is not reconciled, and only the status is reconciled. However, for the case of PG, before reconciling the status, the most recent copy of PerconaPGBackup is not fetched (it was done as a part of the spec reconciliation).
**Solution:**
Get the PerconaPGBackup before updating the status
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1117 | [BUG] fix PG backup status flip-flop

---

api/v1alpha1/databaseclusterbackup_types.go
api/v1alpha1/databaseclusterrestore_types.go
controllers/databaseclusterbackup_controller.go
controllers/databaseclusterrestore_controller.go
gke_gcloud_auth_plugin_cache

---
**Problem:**
EVEREST-1019
The states for backups/restores differ depending on the underlying database operator type.
**Cause:**
The states are read directly from the underlying CRs.
**Solution:**
Add a list of known states, and add a method to unify them based on the underlying CR.

EVEREST-1019 | Unify status for backups and restores

---

controllers/providers/pg/applier.go
controllers/providers/psmdb/applier.go

---
**Problem:**
EVEREST-1145
If users select to enable external access to a DB running in EKS, the provisioned LB should be of the “network” type (NLB) instead of the “classic” type.
**Solution:**
To achieve this, we should set the LB annotation (service.beta.kubernetes.io/aws-load-balancer-type: nlb) in order to provision the AWS network load balancer.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1145 | Add EKS NLB annotations for PSMDB and PG

---

.github/workflows/build-push-images.yaml
.github/workflows/checks.yml
.github/workflows/ci.yml
api/v1alpha1/backupstorage_types.go
api/v1alpha1/databasecluster_types_test.go
api/v1alpha1/monitoringconfig_types.go
controllers/common/helper.go
controllers/databasecluster_controller.go
controllers/databaseclusterrestore_controller_test.go
controllers/databaseengine_controller.go
controllers/providers/pg/pg_test.go
go.mod
main.go
tools/go.mod

Besides bumping go to 1.22, we also removed the unneeded for loop variable copies. See https://go.dev/blog/loopvar-preview for more details on this.

EVEREST-107 bump go version to 1.22

---

api/v1alpha1/databaseclusterrestore_types.go

---
**Problem:**
EVEREST-590
This issue was already fixed in https://github.com/percona/everest-operator/pull/372 , however it has resurfaced (again) after merging https://github.com/percona/everest-operator/pull/410
**Cause:**
In https://github.com/percona/everest-operator/pull/410 , we unified the status of the DBRestore CR. For PXC, states such as `Starting Cluster` was merged under `Running`, and `Stopping Cluster` was merged under `Starting`.
However, in our reconciliation, we depend on explicitly checking the states `Starting Cluster` and `Stopping Cluster`, to handle pausing/unpausing the DB when restoring to a new cluster. Since these states disappeared (into Running/Starting), this logic started to fail.
**Solution:**
For DBBackups related to PXC, we …

EVEREST-590 | Fix regression in PXC restores

---

api/v1alpha1/databaseclusterrestore_types.go
controllers/common/helper.go
controllers/providers/pg/applier.go
controllers/providers/pg/provider.go
controllers/providers/psmdb/applier.go
controllers/providers/psmdb/provider.go
controllers/providers/pxc/provider.go

**Restore status fix**
---
**Problem:**
EVEREST-1167
There was a regression introduced in https://github.com/percona/everest-operator/pull/410 which cased the restoration falsely considered as Complete for psmdb. 
**Cause:**
The operator was still expecting the old upstream-based statuses for the restore objects, that's why the `isComplete()` function, which was checking if the restore is complete based on the restore's status, wasn't working correctly.
It wasn't prominent for engines other than psmdb bc they use the same strings for statuses as the Everest restore does, but psmdb uses different string values.   
**Solution:**
Use the new statuses to figure out if the restore is complete.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1167 Restore status fix

---

controllers/providers/pxc/applier.go

**Problem:**
EVEREST-913
- #324 
- #415 
**Cause:**
When we introduced PXCO 1.14 we forgot to expose the HAProxy Replicas leading to a regression on EVEREST-913
**Solution:**
Expose the HAProxy replicas
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-913 fix HAProxy replicas LB type

---

controllers/databaseclusterbackup_controller.go
e2e-tests/tests/features/dbbackup_pg/20-assert.yaml
e2e-tests/tests/features/dbbackup_pg/30-delete-dbb.yaml
e2e-tests/tests/features/dbbackup_pg/50-assert.yaml
e2e-tests/tests/features/dbbackup_pg/60-delete-dbb.yaml
e2e-tests/tests/features/dbbackup_pg/70-assert.yaml
e2e-tests/tests/features/dbbackup_psmdb/20-assert.yaml
e2e-tests/tests/features/dbbackup_psmdb/30-delete-dbb-s3.yaml
e2e-tests/tests/features/dbbackup_psmdb/31-assert.yaml
e2e-tests/tests/features/dbbackup_psmdb/32-delete-dbb-azure.yaml
e2e-tests/tests/features/dbbackup_psmdb/70-assert.yaml
e2e-tests/tests/features/dbbackup_pxc/20-assert.yaml
e2e-tests/tests/features/dbbackup_pxc/30-delete-dbb.yaml
e2e-tests/tests/features/dbbackup_pxc/50-assert.yaml
e2e-tests/tests/features/dbbackup_pxc/60-delete-dbb.yaml
e2e-tests/tests/features/dbbackup_pxc/70-assert.yaml

---
**Problem:**
EVEREST-859
When uninstalling Everest via the CLI, the DB gets deleted before the backups can be cleaned-up properly
**Cause:**
We're not setting the `foregroundDeletion` finaliser.
**Solution:**
Set the finalizer at the time of performing the cleanup. Currently, the finalizers are added from different places (like from the API server). With this approach, we can unify the clean-up process, so that we don't have to explicitly add finalizers from the API server.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-859 | Ensure backups are deleted in foreground during clean-up

---

controllers/common/consts.go
controllers/databasecluster_controller.go

---
**Problem:**
EVEREST-0
Everest operator crashes when not all DB operators are installed.
- [link]
**Cause:**
The DB controller, during initialisation, adds the DB CRDs to the scheme only if they are installed. However, we are setting up watchers for the CRs without checking if they are recognised by the scheme, which leads to a crash.
**Solution:**
Before setting up the watch, check if the Scheme recognises the CRD. The CRDs are added to the scheme only if they are installed first.

[bug] watchers should be configured only if recognised by the scheme

---

controllers/providers/pxc/applier.go

Reverts percona/everest-operator#429
Due to a [bug in the PXCOperator](https://perconadev.atlassian.net/browse/K8SPXC-1416) we need to revert this PR until it's fixed.
[EVEREST-969]: https://perconadev.atlassian.net/browse/EVEREST-969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert "EVEREST-969: no parallel backups"

---

api/v1alpha1/databaseclusterrestore_types.go
controllers/common/consts.go
controllers/databasecluster_controller.go
controllers/providers/pxc/provider.go

**PXC restoration status update**
---
**Problem:**
EVEREST-1244
**Problem:**
When a PXC cluster is in the "Stopping Cluster" or "Starting Cluster" state during the restoration it's not considered as a restoring status and as a result the FE doesn't block actions over the cluster. 
This behaviour was intentionally introduced in https://github.com/percona/everest-operator/pull/435, because
>  in our reconciliation, we depend on explicitly checking the states Starting Cluster and Stopping Cluster, to handle pausing/unpausing the DB when restoring to a new cluster. Since these states disappeared (into Running/Starting), this logic started to fail. 
**Solution:**
1. revert the https://github.com/percona/everest-operator/pull/435, so Everest would again merge the states such as `Starting …

EVEREST-1244 PXC restoration status fix

---

controllers/databaseclusterbackup_controller.go

**Scheduled dbb creation fix**
---
**Problem:**
EVEREST-1293
Scheduled backup never appear for the second schedule, if the first schedule (which took at least one backup) was deleted. 
**Cause:**
Everest was figuring out the scheduled backup storage name by the pg repo number which is not reliable in all cases. 
**Solution:**
Get the repo name from the `pg-backup`, find the appropriate repo in `pg` and compare the repo configuration with the storages defined in Everest to figure out the Everest  backup storage name.  
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1293 Scheduled dbb creation fix

---

controllers/common/helper.go
controllers/databaseclusterbackup_controller.go
controllers/databaseclusterrestore_controller.go
controllers/providers/pg/pg_repos_reconciler.go
controllers/providers/pg/pg_test.go

**Backups repos reconciliation fix**
---
**Problem:**
EVEREST-1316
Changes:
1. For backups and new schedules: first check if there is any existing repo which can be reused and only if there is none - create a new repo
2. When creating an on-demand backup, rely on the repo name but not on it's index - this approach is more reliable. 
3. Sort the repos by name. When schedules are deleted, the pg cluster might get into the state when it has [repo1, repo3, repo2], so the repos can switch places although they still pointing out to the same bucket as before. It's confusing, so from now on we always sort repos by name
4. Added tests to cover the failing cases.  
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1316 Backups repos reconciliation fix

---

controllers/common/consts.go
controllers/common/helper.go
controllers/providers/pg/provider.go
controllers/providers/psmdb/provider.go
controllers/providers/pxc/provider.go

**Problem:**
EVEREST-1349
DBs created with old versions of the everest-operator get stuck in the "Deleting" state
- #428 
**Cause:**
In PR #428 we removed the dbb-cleanup finalizer because we introduced owner references that automatically delete the objects. However, DBs created with previous versions of the everest-operator will still feature the dbb-cleanup finalizer which needs to be properly handled otherwise the DB will be stuck in the "Deleting" state.
**Solution:**
Revert the removal of the dbb-backup finalizer handling.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1349 Fix DBs stuck in the "Deleting" state

---

controllers/providers/pxc/applier.go
controllers/providers/pxc/mysqld_configs.go
e2e-tests/tests/core/pxc/10-assert.yaml
e2e-tests/tests/core/pxc/30-assert.yaml
e2e-tests/tests/core/pxc/50-assert.yaml
e2e-tests/tests/core/pxc/60-assert.yaml

**Problem:**
EVEREST-1354
PXC pod's resource limits were being overwritten.
- #309
**Cause:**
We were setting preset resource limits values based on the specified memory. This completely overwrites any custom value. 
**Solution:**
* Don't overwrite the resources limits set by the users
* Set the requests to equal the limits
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1354 Fix PXC resources being overwritten

---

controllers/monitoringconfig_controller.go

---
**Problem:**
EVEREST-1264
MonitoringConfigs stopped working after https://github.com/percona/everest-operator/pull/463 was merged.
**Cause:**
https://github.com/percona/everest-operator/pull/463 changes the way how MonitoringConfigs are referenced by the DB. Earlier, MonitoringConfigs and its Secret were created in the same namespace as the VMAgent, i.e, `everest-monitoring.` With https://github.com/percona/everest-operator/pull/463, MonitoringConfigs and its Secret are now created in the DB namespace, and VMAgent can no longer reference the secret since it belongs to a different namespace.
**Solution:**
- Add additional logic to copy the Secret to the `everest-monitoring` namespace
- Secret is automatically cleaned up with the help of a finalizer
**CHECKLIST** …

EVEREST-1264 | Fix Secret reconciliation for MonitoringConfig controller

---

controllers/providers/psmdb/applier.go

**Apply default affinity rules for mongos**
---
**Problem:**
EVEREST-1305
DB can stuck with:
```
mongos:
message: '0/1 nodes are available: 1 node(s) didn''t match pod anti-affinity rules.
```
**Cause:**
If there are no rules applied to `.spec.sharding.mongos`, then the `requiredDuringSchedulingIgnoredDuringExecution` with `topologyKey: kubernetes.io/hostname` is applied by the operator. 
**Solution:**
Apply the default `preferredDuringSchedulingIgnoredDuringExecution` rule for `.spec.sharding.mongos` as Everest does for other pods. The rule is not that strict and schedules pods to the different nodes _if possible_
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1305 Apply default affinity rules for mongos

---

controllers/providers/psmdb/applier.go

**Default mongos size**
---
**Problem:**
EVEREST-1404
As discussed with experts, it makes sense to set a default value for mongos equal to the nodes amount. 
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1404 Default mongos size

---

controllers/common/helper.go
e2e-tests/tests/upgrade/pg/90-delete-clusters.yaml
e2e-tests/tests/upgrade/psmdb/90-delete-cluster.yaml
e2e-tests/tests/upgrade/pxc/90-delete-cluster.yaml

**Deleting status fix**
---
**Problem:**
EVEREST-1415
Everest cluster does not follow the further upstream cluster statuses after deletion. As a result if the upstream cluster deletion takes long (for example, a sharded psmdb cluster with 5 nodes), the psmdb cluster hangs in the “stopping“ state but in Everest there is no DatabaseCluster shown anymore as if it is deleted. 
**Cause:**
Everest has this `everest.percona.com/upstream-cluster-cleanup` finalizer which ensures that the upstream cluster deletion is triggered and after this deletion Everest removes the finalizer  which unblocks the DatabaseCluster CR deletion. So the DatabaseCluster CR is deleted but the upstream psmdb still exists in the “stopping“ state. 
**Solution:**
Do not remove the …

EVEREST-1415 Deleting status fix

---

controllers/databasecluster_controller.go

---
**Problem:**
EVEREST-1414
Everest operator removes any extra labels that are not managed by it. This is a bit of a problem when the Everest resources are managed by anther operator/entity. For example, when deploying with ArgoCD, it adds an extra `app.kubernetes.io/instance` label, however Everest operator removes it.
**Cause:**
The `reconcileLabels` logic is written in such a way that it keeps only those labels that the Everest operator needs.
**Solution:**
Re-write the code so that existing labels are merged with the ones Everest needs.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1414 | DBC controller should not modify labels set by other operators

---

controllers/providers/pg/applier.go
controllers/providers/pg/pg_repos_reconciler.go
controllers/providers/pg/pg_test.go

**Fix PG use the same bucket**
---
**Problem:**
EVEREST-1427
When a scheduled backup is running, Everest tries to figure out the backup storage name from bucket, url and region, which is a problem when there are storages with the same bucket in different namespaces. 
**Solution:**
Everest should not only compare the bucket, url and region but also check that the backupstorage namespace matches the db namespace
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1427 Fix PG use the same bucket

---

api/v1alpha1/databasecluster_types.go
bundle/manifests/everest-operator.clusterserviceversion.yaml
bundle/manifests/everest.percona.com_databaseclusters.yaml
config/crd/bases/everest.percona.com_databaseclusters.yaml
controllers/databasecluster_controller.go
controllers/providers/pxc/applier.go
deploy/bundle.yaml

---
**Problem:**
EVEREST-1424
Cannot update PXC resource settings after adding the restart protection mechanism in https://perconadev.atlassian.net/browse/EVEREST-1424
- https://perconadev.atlassian.net/browse/EVEREST-1424
For more details, see comment https://github.com/percona/everest-operator/pull/511#discussion_r1751444476
**Cause:**
In the above mentioned PR, the resource settings for PXC are preserved if the DB is in running state. This means, that while there will not be any restarts when ugprading to 1.2.0, a user also cannot update these settings because the DB is running, and the older settings are preserved/overwritten.
**Solution:**
Add an additional check to detect when the DB spec may have potentially changed. We do this by tracking …

EVEREST-1424 | Cannot apply PXC resource settings after adding restart protection mechanism

---

controllers/databaseclusterbackup_controller.go

**Fix pg scheduled backups when using the same bucket**
---
**Problem:**
EVEREST-1427 
Backup storages using the same bucket in different namespaces got mixed up in the pg scheduled backups, so scheduled backups got stuck
https://github.com/percona/everest-operator/pull/512 fixed how Everest figures out the storage name in reconciliation, however it didn't fix how Everest figures out the storage when a new scheduled backup appears. This PR fixes it. 
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1427.2 Fix pg scheduled backups

---

controllers/databaseclusterrestore_controller.go

---
**Problem:**
EVEREST-1466
PITR restores for PXC was getting stuck.
**Cause:**
Earlier we refactored the code so that BackupStorages are read from the DB namespaces, however there was some code that was not refactored for this change.
**Solution:**
Fix the code that was reading the BackupStorage from `everest-system` instead of the DB namespace.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1466 | [bugfix] Get BackupStorage from DB namespace for PXC PITR restore

---

controllers/common/helper.go
controllers/providers/pg/applier.go

**Problem:**
EVEREST-1523
Upgrading to PGO v2.4.1 fails.
**Cause:**
PGO v2.4.1 changed the `.spec.extensions.image` to be required so CRs without it were causing the OLM install plan to fail.
**Solution:**
Even though `.spec.extensions` is set to be optional, we use the golang struct to generate the default PG spec and since `.spec.extensions` is a value and not a pointer we generate an empty struct which violates the required restriction on the `image` field. By setting this field we ensure that by the time users trigger an upgrade to v2.4.1 the existing CRs already have the field and thus the install plan succeeds.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1523 add required PG extensions image field

---

api/v1alpha1/databasecluster_types.go
controllers/providers/pg/applier.go

---
**Problem:**
EVEREST-1434
PG DBs restart after upgrading the PG operator to 2.4.1
**Cause:**
- In https://github.com/percona/everest-operator/pull/511, we added a workaround to ensure that the new affinity settings are applied only on those clusters which are in the initialising state.
- Due to a new change added in PGO 2.4.1, PG DBs briefly go into the "initialising" state even though no pods are actually restart.
- Due to this brief change in state, Everest operator applies the new affinity settings on the DB pods, which results in a complete restart.
**Solution:**
- Do not depend on this "initialising" state
- Apply new affinity settings only if the following conditions are met
- the cluster is a new cluster (i.e, no state reported yet)
- for existing …

EVEREST-1434 | Fix PG DB restarts after upgrading PGO to 2.4.1

---

Dockerfile

A new package was added in https://github.com/percona/everest-operator/pull/534 due to which docker builds were left broken. This PR fixes the Dockerfile

Fix broken docker builds

---

bundle/manifests/everest-operator.clusterserviceversion.yaml
config/manager/manager.yaml
config/rbac/role.yaml
controllers/databaseengine_controller.go
deploy/bundle.yaml
main.go

---
**Problem:**
https://github.com/percona/everest-operator/pull/534 provides a way to dynamically watch namespaces based on labels, rather than setting the `DB_NAMESPACES` var. However, using this mechanism causes the DB reconciliation to get stuck.
**Cause:**
When bootstrapping the various controllers, we add watches to the DB CRs only if the CRDs exist first. This step happens only once, before the controller is started. With https://github.com/percona/everest-operator/pull/534, we're now allowed to start the operator without the DB namespaces. This means that when the controller starts, none of the DB CRDs exist, and as a result, the controllers are never watching the DB CRs.
This did not happen earlier because when you update the `DB_NAMESPACES` var, it leads …

EVEREST-1511 | Restart operator pod if new DB CRDs are installed

---

main.go

---
**Problem:**
EVEREST-1585
DBEngines are created in everest-system and everest-monitoring namespaces
**Cause:**
In https://github.com/percona/everest-operator/pull/534 we introduced a new mechanism to reconcile DB namespaces using label filters and eliminating the need for manually setting the DB_NAMESPACES env variable. However, this filter had the system namespaces hard-coded to always allow them. As a result, the DBEngines controller always created the DBEngines in those namespaces. 
**Solution:**
Remove the hard-coded system namespaces from the filter. 
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1585 | Remove system namespaces from namespace filter

---

controllers/providers/psmdb/applier.go
e2e-tests/tests/features/dbbackup_psmdb/10-assert.yaml

**Update default PBM startingStatus for new clusters**
---
**Problem:**
EVEREST-1598
The error `couldn''t get response from all shards: convergeClusterWithTimeout: 33s:` can appear for sharded clusters (see EVEREST-1594). There is no certainty why exactly it appears, but the more shards the cluster has the bigger is the chance to face that limit. 
As discussed with experts, it would make sense to increase the default timeout. There's no strict recommendations which new default value to use, so it was decided to use 120s as there were a couple of cases when it helped in the past. 
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1598 Update pbm startingStatus interval

---

controllers/providers/psmdb/applier.go

**Allow editing of the sharding parameters**
---
**Problem:**
EVEREST-1330
Editing of the sharding parameters wasn't allowed, since at some point we decided to release only the _enabling for new clusters_ functionality. Since then at some point it was decided to release the editing as well, however the implementation for editing was not implemented. 
Note: scaling down the number of shards still does not take any effect, bc it's not clear how it should work, how it will affect the data, if there are any additional preparation steps needed to perform and finally - if it's even a valid use case. Figuring it out with experts. 
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1330 Allow editing of the sharding parameters

---

.github/workflows/build-push-images.yaml

---
**Problem:**
EVEREST-107
At some point trivy started to fail the pipelines from time to time bc of the `TOOMANYREQUESTS` error. There are several workarounds but none of them 100% guarantee. 
Since we have Snyk which also scans for vulnerabilities, I don't think it's worth to go through all the "try and fail" path with workarounds, let's solve it ultimately - remove trivy scans from the Everest pipelines. 
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-107 Remove trivy

---

controllers/providers/pxc/applier.go

---
**Problem:**
EVEREST-1700
- PXC did not fill in missing fields for a PMM secret before if it was already created. Now it does.
**Solution:**
- Create the secret if it does not exist
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1700: create secret if it does not exist

---

.github/workflows/build-push-images.yaml

After merging #597 the builds started failing. Example: https://github.com/percona/everest-operator/actions/runs/12138839528/job/33845128550
This is because we forgot to update the operator-sdk version in the build pipeline

EVEREST-107 fix builds

---

internal/controller/databaseengine_controller.go

---
**Problem:**
EVEREST-1818
DBEngine reconciler complains CSV NotFound when reconciling the status.
**Cause:**
DBEngine reconciler tries to get the CSV based on the `.status.OperatorVersion` of the given DBEngine. However, this field is set only after the DB operator deployment is ready. Until then it keeps reporting these not found errors.
**Solution:**
Set the `.status.OperatorVersion` field even if the deployment is not ready.
**CHECKLIST**
---
**Helm chart**
**Jira**
**Tests**

EVEREST-1818 | fix DBEngine status reconciliation

---

api/v1alpha1/databasecluster_types.go
internal/controller/providers/pg/provider.go
internal/controller/providers/psmdb/provider.go
internal/controller/providers/pxc/provider.go

**Add "Creating" DB status**
---
**Problem:**
EVEREST-1814
**Problem:**
The DB can be in an ‘unknown’ state for a couple of seconds and we didn't want to show that to the user. 
**Solution:**
The upstream operators have the different statuses when a cluster is being created: 
- pxc - "unknown"
- psmdb - ""
- pg does not have any empty status.
So the upstream statuses are different although Everest maps the DB status to the upstream cluster status 1:1. There is no point so far to create a separate mapping for each upstream operator only because we want to unify AppStateCreating, so in this PR the Everest operator unifies the "" and "unknown" statuses into the "creating" status. 
**Related PRs:** 
- https://github.com/percona/everest/pull/1084
**CHECKLIST**
---
**Helm chart**
**Jira** …

EVEREST-1814 add creating state

---

api/v1alpha1/databasecluster_types.go
bundle/manifests/everest-operator.clusterserviceversion.yaml
bundle/manifests/everest.percona.com_databaseclusters.yaml
config/crd/bases/everest.percona.com_databaseclusters.yaml
deploy/bundle.yaml
internal/controller/databasecluster_controller.go
internal/controller/providers/pg/applier.go
internal/controller/providers/psmdb/applier.go
internal/controller/providers/pxc/applier.go

**Do not use db.spec.backup.enabled**
---
**Problem:**
EVEREST-1628
The field `db.spec.backup.enabled` is confusing, Everest basically doesn't have such a feature as disabling backups, the field was using instead of checking the number of schedules. 
**Solution:**
Instead of using `db.spec.backup.enabled` Everest looks at the number of schedules which keeps the logic.   
- https://github.com/percona/everest/pull/1087
**CHECKLIST**
---
**Helm chart**
**Jira**
**Tests**

EVEREST-1628 Do not use db.spec.backup.enabled

---

Makefile

---
**Problem:**
Add possibility to build Everest operator with debug flags. It will be used for remote debugging.
- [link]

Add `build-debug` target to Makefile

---

.github/workflows/checks.yml

**Update ubuntu images**
---
**Problem:**
EVEREST-1883
The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025 == no workflow execution if there is runs-on: ubuntu-20.04
Everest operator doesn't use `ubuntu-20.04` however for the sake of alignment with other repos, let's use `ubuntu-latest` and do not return to the problem anymore
- https://github.com/percona/everest/pull/1236
- https://github.com/percona/everest-catalog/pull/57

EVEREST-1883 update ubuntu images

---

api/v1alpha1/databasecluster_types.go
internal/controller/common/helper.go
internal/controller/common/helper_test.go
internal/controller/providers/pg/provider.go
internal/controller/providers/psmdb/provider.go
internal/controller/providers/pxc/provider.go

**Add volume resize error conditions**
---
**Problem:**
EVEREST-1869
Since the resizing volumes can be a long operation with potential errors from the CSI driver we need to make these errors available to our users. 
- https://github.com/percona/percona-helm-charts/pull/509
- https://github.com/percona/everest/pull/1261
**CHECKLIST**
---
**Helm chart**
**Jira**
**Tests**

EVEREST-1869 Add volume resize error conditions

---

internal/controller/databasecluster_controller.go

PXC clusters sometimes do not show `restoring` state when a restore is in-progress
In https://github.com/percona/everest-operator/pull/739 we merged a change where the reconciliation loop does an early exit if there is a restore in-progress. This was done to skip reconciliation in order to avoid interfering with the pxc-operator during the restore. 
As an unintended side-effect, this also resulted in the status updates being skipped. This meant that even though a restore was in progress, the DB status was not updated to show it.
Ensure that status is always reconciled regardless of the early exit. We do this by moving the status update code up ahead into a defer block.

EVEREST-2011 | Fix issue with DB status not getting reconciled

---

internal/controller/databasecluster_controller.go

Possible typo introduced from https://github.com/percona/everest-operator/pull/697

EVEREST-107 | Fix typo in requeue logic

---

api/v1alpha1/databasecluster_types.go
bundle/manifests/everest-operator.clusterserviceversion.yaml
internal/consts/annotations.go
internal/controller/databaseclusterrestore_controller.go
internal/data-importer/cmd/pg/import.go
internal/data-importer/cmd/psmdb/import.go
internal/data-importer/cmd/pxc/import.go
internal/data-importer/deploy/psmdb/dataimporter.yaml

1. Upstream restore objects created by data importers are orphan and cannot be deleted
2. DBR created for PGRestore created by data importers
1. Attach owner ref to DB, so that it is automatically deleted when DB is deleted.
2. Add an annotation to skip creating DBR

EVEREST-2006 | DataImporter improvements

---

internal/controller/dataimportjob_controller.go

---
**Problem:**
EVEREST-2155
The PG DataImportJob remains in `Error` state for a long time before eventually transitioning to `Succeeded`
**Cause:**
* The PG DataImportJob "re-creates" the upstream `PerconaPGCluster` object
* As a part of this re-creation, the user Secret temporarily goes missing (PG operator deletes it)
* The DataImportJob Controller tries to actively reconcile a payload Secret for which it requires this user secret. If this user secret is missing, it complains and moves to `Error`
* The Secret is eventually created, so the job then transitions to `Succeeded`
**Solution:**
* Do not attempt to reconcile the request payload Secret if it already exists with the desired keys. This payload Secret is already created once during the job initialisation, …

EVEREST-2155 | Check if DataImportJob payload Secret exists before attempting to reconcile it

---

internal/controller/databasecluster_controller.go

---
**Problem:**
EVEREST-2148
This problem was initially discovered during testing of data importer, when the UI created the user credentials secret using a different naming format from everest-operator (`everest-secrests-xx`)
When a different naming format was used by the UI for the creation of this secret, restore into new DB would fail.
**Cause:**
The copy/restore to new DB logic requires the original user secret from the source DB to be copied. However, it searches for the secret based on a hard-coded naming format rather than looking it up from the DB spec.
**Solution:**
Instead of assuming a certain naming format for the secret, it should lookup the actual name of the source secret from the DB spec.
**CHECKLIST**
---
**Helm chart**
**Jira**
**Tests**

EVEREST-2148 | improve secret copying logic when restoring to new DB

---

Dockerfile
Makefile
bundle/manifests/everest-operator.clusterserviceversion.yaml
config/manager/manager.yaml
deploy/bundle.yaml
internal/consts/version.go
internal/controller/common/helper.go
internal/controller/providers/pxc/applier_test.go
internal/migrate/main.go
internal/migrate/migrator/migrator.go
internal/migrate/migrator/migrator_test.go
internal/webhooks/databasecluster.go
internal/webhooks/load_balancer_config.go
utils/finalizers.go
utils/validators.go
utils/validators_test.go

**Add the migrator initContainer**
---
**Problem:**
EVEREST-2177
In this PR:
1. **Added a new binary for migrator** 
Migrator is included as a separate binary with its own endpoint into the everest-operator image. Everest-operator now has initContainer that always tries to run the migrator. The migrator uses the Lease object to track wether the migration was already done (by checking annotations which contain the last version) and if so it does nothing. If the migration wasn't done, the migrator checks if the k8s type is EKS and if so - adds the loadBalancerConfigName = "eks-default" to all exposed DB clusters. 
3. **Removed the "Unstructured" layer.**  
Previously when Everest was checking the k8s type it was getting the `StorageClassList` using `Unstructured`. It was so seems the very …

EVEREST-2177 Add initContainer

---

internal/webhooks/monitoringconfig.go

---
**Problem:**
EVEREST-2217
MonitoringConfig validation webhook can sometimes fail to fetch Secret even though it exists. This generally occurs only after 1 MonitoringConfig already exists.
**Cause:**
* The validation webhook uses the default client to fetch the MonitoringConfig Secret. This client reads from the cache.
* The first MonitoringConfig always succeeds because caching has not yet started for Secrets, so the read it performed directly from the API server. However, when the second MonitoringConfig is created, it starts reading from the client cache.
* It is possible for the validation webhook to be called before the cache has had the time to sync with the Kube API server. As a result, it thinks that the Secret does not exist.
**Solution:**
Use …

EVEREST-2217 | Use APIReader for fetching MonitoringConfig Secret in validation webhook

---

Makefile
internal/controller/providers/pg/applier.go
internal/controller/providers/psmdb/applier.go
internal/controller/providers/pxc/applier.go
tests/e2e/core/pg/10-assert.yaml
tests/e2e/core/pg/50-assert.yaml
tests/e2e/core/psmdb/10-assert.yaml
tests/e2e/core/psmdb/50-assert.yaml
tests/e2e/core/pxc/10-assert.yaml
tests/e2e/core/pxc/50-assert.yaml
tests/integration/core/pg/10-assert.yaml
tests/integration/core/pg/40-assert.yaml
tests/integration/core/psmdb/10-assert.yaml
tests/integration/core/psmdb/40-assert.yaml
tests/integration/core/pxc/10-assert.yaml
tests/integration/core/pxc/40-assert.yaml
tests/integration/features/monitoringconfig_pg/10-assert.yaml
tests/integration/features/monitoringconfig_pg/50-assert.yaml

---
**Problem:**
EVEREST-2233
Upstream DB CRs in most cases have `imagePullPolicy=Always` even for DB engine images. That leads to the following problems:
1. DB cluster restoration after some node failure takes more time because the images need to be re-fetched on each Pod creation.
2. Big companies/users that have a common external IP may face with "DockerHub Rate Limits" issues.
2.1. Image download speed  from DockerHub is not stable and may vary in time -> increases DB cluster restoration time after Node failure.
4. Our tests that create/destroy DB clusters massively are unstable due to unpredictable Pod creation time and "Rate limit" problems
**Solution:**
The images are tagged and  stable so there is no need to re-fetch them …

EVEREST-2233 Set ImagePullPolicy=IfNotPresent for upstream DB images

---

internal/controller/providers/pg/applier.go
internal/controller/providers/psmdb/applier.go
internal/controller/providers/pxc/applier.go
tests/e2e/core/psmdb/10-assert.yaml
tests/e2e/core/psmdb/30-assert.yaml
tests/e2e/core/psmdb/50-assert.yaml
tests/e2e/core/psmdb/60-assert.yaml
tests/e2e/db-upgrade/psmdb/10-assert.yaml
tests/e2e/db-upgrade/psmdb/20-assert.yaml
tests/e2e/db-upgrade/psmdb/30-assert.yaml
tests/e2e/db-upgrade/psmdb/40-assert.yaml
tests/e2e/db-upgrade/psmdb/50-assert.yaml
tests/e2e/operator-upgrade/psmdb/10-assert.yaml
tests/e2e/operator-upgrade/psmdb/20-assert.yaml
tests/e2e/operator-upgrade/psmdb/30-assert.yaml
tests/e2e/operator-upgrade/psmdb/31-assert.yaml
tests/integration/core/psmdb/10-assert.yaml
tests/integration/core/psmdb/11-assert.yaml
tests/integration/core/psmdb/20-assert.yaml
tests/integration/core/psmdb/40-assert.yaml
tests/integration/core/psmdb/41-assert.yaml

**Handle annotations removal**
---
**Problem:**
EVEREST-2264
Everest wasn't handling properly the case of switching from `LoadBalancer` expose type to `ClusterIP`. 
However as it turned out, the annotations can be effectively removed only for `pg`, but the `pxc` and `psmdb` operators do not allow to delete the annotations by design (there was some reason for it which the Cloud team can't remember so far). 
As discussed with the Cloud team, there should be no harm in keeping the annotations when we change to the expose type to ClusterIP, they just will be ignored. So looks like we need to accept it as a limitation in Everest until it's fixed in the upstream. 
psmdb ticket https://perconadev.atlassian.net/browse/K8SPSMDB-1441
pxc ticket https://perconadev.atlassian.net/browse/K8SPXC-1709 …

EVEREST-2264 Handle annotations removal

---

cmd/main.go

---
**Problem:**
EVEREST-2279
When updating the TLS certificate secret, Everest operator is not able to watch the change and refresh the certificate used by the admission webhook server.
**Cause:**
The TLS cert watcher is not started.
**Solution:**
Call `webhookCertwatcher.Start(..)`
**CHECKLIST**
---
**Helm chart**
**Jira**
**Tests**

EVEREST-2279 | [BUG] TLS cert watcher is not started
