percona/everest-operator

controllers/databasecluster_controller.go
controllers/databaseclusterbackup_controller.go
controllers/databaseclusterrestore_controller.go

EVEREST-125
Add support PG restores

EVEREST-125 Add support PG restores

---

controllers/databaseclusterrestore_controller.go

EVEREST-250 Add labels to the restore CR
Needed to list restores properly

EVERESST-250 Add labels to the restore CR

---

.golangci.yml
controllers/databasecluster_controller.go
controllers/databaseclusterbackup_controller.go
controllers/databaseclusterrestore_controller.go
controllers/pg_config.go
controllers/version_service.go
go.mod
main.go

---
**Problem:**
EVEREST-434
- https://github.com/percona/percona-everest-backend/pull/171
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-434 Move to errors package

---

controllers/databasecluster_controller.go

---
**Problem:**
EVEREST-561 
- [link]
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-561 Make NLB as the default Loadbalancer for EKS

---

controllers/databasecluster_controller.go
controllers/databasecluster_controller_test.go
controllers/suite_test.go

---
**Problem:**
EVEREST-107
Fixing linter errors after go-lint upgrade
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-107 Fixed linter errors after upgrade

---

Makefile
api/v1alpha1/backupstorage_types.go
bundle/manifests/everest-operator.clusterserviceversion.yaml
bundle/manifests/everest.percona.com_backupstorages.yaml
config/crd/bases/everest.percona.com_backupstorages.yaml
config/manager/kustomization.yaml
deploy/bundle.yaml

---
**Problem:**
EVEREST-574
During the revamping of the information we store we miss description for the operator 
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-574 Store description for backup storage

---

api/v1alpha1/databasecluster_types.go
bundle/manifests/everest-operator.clusterserviceversion.yaml
bundle/manifests/everest.percona.com_databaseclusters.yaml
config/crd/bases/everest.percona.com_databaseclusters.yaml
deploy/bundle.yaml

**Update required fields**
---
EVEREST-518
Update the PITR "enabled" field to be required 
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-518 PITR API update

---

bundle/manifests/everest-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/backupstorage_controller.go
deploy/bundle.yaml

---
**Problem:**
EVEREST-0
- [link]
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-496 Fixed RBAC for namespaces

---

e2e-tests/tests/features/multinamespace_pg/90-delete-clusters.yaml
e2e-tests/tests/features/multinamespace_psmdb/90-delete-cluster.yaml
e2e-tests/tests/features/multinamespace_pxc/90-delete-cluster.yaml

---
**Problem:**
EVEREST-107
- [link]
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-107 Fixed tests for multinamespace

---

controllers/databasecluster_controller.go
controllers/databasecluster_controller_test.go

> **CHANGE DESCRIPTION**
---
**Problem:**
EVEREST-107
- [link]
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-107 Fixed unit tests

---

.github/workflows/build-push-images.yaml

**Push operator dev image**
---
**Problem:**
EVEREST-405
Push operator dev image

EVEREST-405 Operator dev image

---

.github/workflows/ci.yml
e2e-tests/tests/core/pg/10-assert.yaml
e2e-tests/tests/core/pg/20-assert.yaml
e2e-tests/tests/core/pg/30-assert.yaml
e2e-tests/tests/core/pg/50-assert.yaml
e2e-tests/tests/core/pg/80-assert.yaml

---
**Problem:**
EVEREST-107
Upgrade PG Operator to 2.3.1
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-107: PG Operator 2.3.1

---

controllers/databasecluster_controller.go

**Fix missing monitoring label**
---
**Problem:**
EVEREST-805
We were deleting the monitoring label by accident.
**Solution:**
Ignore the monitoring label when cleaning up.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-805 Fix missing monitoring label

---

controllers/databaseclusterbackup_controller.go

**Don't delete scheduled backups from s3**
---
**Problem:**
EVEREST-838
Scheduled backups were being deleted from s3.
**Cause:**
By default the pxc and psmdb operators set a finalizer for the scheduled backup.
**Solution:**
We don't want to delete these backups from s3 so we remove the finalizer.
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-838 Don't delete scheduled backups from s3

---

controllers/databasecluster_controller.go
controllers/haproxy_config.go

**Fix HAProxy config**
---
**Problem:**
EVEREST-934
In https://github.com/percona/everest-operator/pull/309 we merged changes related to HAProxy config. This PR had 2 issues:
- Incomplete/partial haproxy cfg file
- Wrongly computed resource requirements for HAProxy
**Solution:**
This PR fixes the above problems and uses the newly computed resource requests provided in [this](https://perconadev.atlassian.net/browse/EVEREST-824) ticket

EVEREST-934 | Fix issues with HAProxy config

---

.github/workflows/ci.yml

**Update CI cleanup**
---
**Problem:**
EVEREST-107
the `psmdb` was called twice, however pg was never called.

EVEREST-107 update ci cleanup

---

controllers/providers/pxc/provider.go

---
**Problem:**
EVEREST-590
https://github.com/percona/everest-operator/pull/372 did not completely fix the issue with restores, as they still fail intermittently. 
**Cause:**
There is a bug with how we observe PXC restores and set the pause on the cluster. When performing a PXC restore, the PXC operator pauses the cluster. In order to avoid Everest from overwriting this pause state, it checks for on-going restores first and sets a pause state depending on that. However, the existing logic here has a bug where the PXC operator can pause the cluster between the time Everest has read the PXC object and inspected the PXC restores. In this scenario, Everest will unpause the cluster and the restore will be stuck forever.
**Solution:**
Explicitly reconcile the pause …

EVEREST-590 | improve pause/unpause state of PXC cluster during restore

---

controllers/providers/pxc/applier.go

---
**Problem:**
EVEREST-969
Do not allow parallel backups

EVEREST-969: no parallel backups

---

controllers/databaseclusterbackup_controller.go

---
**Problem:**
EVEREST-1092
We must prevent on-demand backups from running when a scheduled backup is running. Everest server does this by listing dbbackup objects, and if there are any in state `Running`, it rejects the request. However, this does not work correctly for PSMDB.
- https://github.com/percona/everest-operator/pull/400
**Cause:**
Due to a known limitation in PSMDB operator, we avoid creating a dbbackup object for a scheduled psmdb-backup unless it has progressed beyond the `waiting` state. As a side-effect, the creation of the dbbackup object is delayed. Going back to the original problem in EVEREST-1092, this means that even though the `psmdb-backup` object exists for a schedule, Everest allows creation of an on-demand …

EVEREST-1092 | Re-implement PSMDB backup workaround

---

api/v1alpha1/databasecluster_types.go

---
**Problem:**
EVEREST-1194
A subnet suffix was not properly added to an IP address.
**Cause:**
Bug in the code which did not reference the correct value
**Solution:**
Fix the bug
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1194: fix IP address without range

---

controllers/databaseclusterbackup_controller.go

**Use PG .status.backupName**
---
**Problem:**
EVEREST-1353
To figure out the PG backup destination Everest needed to list objects in s3 storage. Now there is this `.status.backupName` field which can be used for this purpose. If there is no such field in the `pg-backup`s status, Everest still lists objects in S3
**Related PRs:**
- https://github.com/percona/everest/pull/683 (improve validation)
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1353 use PG .status.backupName

---

controllers/providers/psmdb/applier.go

---
**Problem:**
EVEREST-1575
Upgrading to PSMDBO 1.17.0 leads to a restart of the PSMDB clusters.
**Cause:**
The PBM image changes when we upgrade the PSMDBO version. Since this image is used to run the backup-agent within the DB pods as a sidecar, changing it leads to a restart of the DB pods.
**Solution:**
Preserve the old image until the CRVersion has been updated.
**CHECKLIST**
---
**Jira**
**Tests**

[BUGFIX] PSMDB clusters are restarted after upgrading operator to 1.17.0

---

controllers/providers/psmdb/applier.go

---
**Problem:**
EVEREST-1310
I tested https://github.com/percona/everest-operator/pull/574 only for existing clusters and didn't realize it broke the creation flow bc of panics
This PR sets the default spec for sharding if it's not set and fixes the panic
**CHECKLIST**
---
**Jira**
**Tests**

EVEREST-1310 Fix creating sharded clusters

---

.github/workflows/build-push-images.yaml
.github/workflows/checks.yml
.github/workflows/ci.yml
Dockerfile
go.mod
internal/controller/common/helper_test.go
tools/go.mod

**Update go version to 1.24**
---
**Problem:**
EVEREST-107

EVEREST-107 update go version to 1.24

---

.github/workflows/auto-update-base.yaml

This workflow runs on every commit pushed to main and updates the base branch of every PR labeled with auto-update-base.
It was copied from https://github.com/percona/everest/blob/main/.github/workflows/auto-update-base.yaml

EVEREST-107 Add workflow for auto-updating PR's base branch

---

api/v1alpha1/databasecluster_types.go
bundle/manifests/everest-operator.clusterserviceversion.yaml
config/rbac/role.yaml
deploy/bundle.yaml
internal/controller/databasecluster_controller.go
internal/controller/providers/pg/provider.go
internal/controller/providers/psmdb/provider.go
internal/controller/providers/pxc/provider.go

**Add upgrading state**
---
**Problem:**
EVEREST-1930
- https://github.com/percona/everest/pull/1235
- https://github.com/percona/percona-helm-charts/pull/502
**CHECKLIST**
---
**Helm chart**
**Jira**
**Tests**

EVEREST-1930 Add upgrading state

---

internal/controller/databasecluster_controller.go

**Dynamically watch crunchy operator resource**
---
**Problem:**
EVEREST-1966 
The issue is a regression introduced in EVEREST-1869 (manual storage expansion support) 
Everest operator is crashing if no PG operator was installed
**Cause:**
In order to support manual storage expansion for pg and receive the volume resizing status, the `everest-operator` was watching `crunchyv1beta1.PostgresCluster`. However if the PG operator wasn't installed during the Everest installation then there is no `crunchyv1beta1.PostgresCluster` resource as well, so the `everest-operator` was crashing.  
**Solution:**
Watch `crunchyv1beta1.PostgresCluster` only if the pg database engine is installed.  
**CHECKLIST**
---
**Helm chart**
**Jira**
**Tests**

EVEREST-1966 Dynamically watch crunchyv1beta1.PostgresCluster

---

.github/dependabot.yml

Add `auto-update-base` label on PRs that are created by dependabot

Adjust dependabot config

---

.github/workflows/build-push-images.yaml
.github/workflows/ci.yml
Makefile
api/v1alpha1/podschedulingpolicy_types.go
bundle.Dockerfile
bundle/manifests/everest-operator.clusterserviceversion.yaml
bundle/manifests/everest.percona.com_backupstorages.yaml
bundle/manifests/everest.percona.com_databaseclusterbackups.yaml
bundle/manifests/everest.percona.com_databaseclusterrestores.yaml
bundle/manifests/everest.percona.com_databaseclusters.yaml
bundle/manifests/everest.percona.com_databaseengines.yaml
bundle/manifests/everest.percona.com_monitoringconfigs.yaml
bundle/manifests/everest.percona.com_podschedulingpolicies.yaml
bundle/metadata/annotations.yaml
config/crd/bases/everest.percona.com_backupstorages.yaml
config/crd/bases/everest.percona.com_databaseclusterbackups.yaml
config/crd/bases/everest.percona.com_databaseclusterrestores.yaml
config/crd/bases/everest.percona.com_databaseclusters.yaml
config/crd/bases/everest.percona.com_databaseengines.yaml
config/crd/bases/everest.percona.com_monitoringconfigs.yaml
config/crd/bases/everest.percona.com_podschedulingpolicies.yaml
deploy/bundle.yaml

- update operator SDK version
- update OPM version
- update kustomize version
- update controller-gen version
- some improvments in Makefile

Update versions of deployment tools
